/** @format */

import "../globals.css";
import { cn } from "../../lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideNavbar from "@/components/SideNavbar";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function Layout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={cn(
      "min-h-screen w-full bg-white text-black flex overflow-x-hidden",
      inter.className,
      {
        "debug-screens": process.env.NODE_ENV === "development"
      }
    )}>
      <SideNavbar />
      {/* main page */}
      <div className="p-8 w-full">{children}</div>
    </main>
      // <body
        // className={cn(
        //   "min-h-screen w-full bg-white text-black flex ",
        //   inter.className,
        //   {
        //     "debug-screens": process.env.NODE_ENV === "development"
        //   }
        // )}
      // >
        // {/* <ThemeProvider
        //   attribute="class"
        //   defaultTheme="system"
        //   enableSystem
        //   disableTransitionOnChange children={undefined}          /> */}

        // {/* sidebar */}
        // {/* <p className="border">Sidebar</p> */}
        // {/* <ModeToggle/> */ }
        
        
      
   
  );
}